# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:16.2
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tpch-db
      POSTGRES_PASSWORD: bigdataclass
    ports:
      - 5432:5432
    restart: always

  jupyter:
    build: ./jupyter_docker
    volumes:
      - ./:/home
    ports:
      - 8888:8888
    working_dir: /home
    restart: always
