# Use root/example as user/password credentials
version: '2'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: no

  mongo-express:
    image: mongo-express
    restart: no
    ports:
      - 8081:8081
